name: Build Android APK (Qt for Python)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  QT_VERSION: '6.5.0'
  PY_VERSION: '3.11'
  JAVA_VERSION: '17'
  PYSIDE_VERSION: '6.5.0'
  ANDROID_PLATFORM: 'android-33'
  ANDROID_BUILD_TOOLS_VERSION: '33.0.2'
  ANDROID_NDK_VERSION: '25.1.8937393'
  ANDROID_CMDLINE_TOOLS_VERSION_URL: 'https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip'
  ANDROID_HOME: ${{ github.workspace }}/android-sdk
  ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

jobs:
  build-android-qt:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Java JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}

    - name: Set up Python ${{ env.PY_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PY_VERSION }}

    - name: Install Python Build Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyside6==${{ env.PYSIDE_VERSION }}
        pip install aqtinstall
        pip install molmass beautifulsoup4 bs4 certifi charset-normalizer defusedxml humanize idna patch py7zr requests semantic-version soupsieve typing-extensions urllib3

    - name: Verify and Validate JSON Config
      run: |
        JSON_CONFIG="qt_for_python_android_deploy.json"
        if [ ! -f "$JSON_CONFIG" ]; then
          echo "ERROR: $JSON_CONFIG not found in the repository root!"
          exit 1
        fi
        echo "$JSON_CONFIG found. Validating..."
        python -m json.tool "$JSON_CONFIG" > /dev/null
        echo "JSON config is valid."
        echo "--- Contents of $JSON_CONFIG ---"
        cat "$JSON_CONFIG"
        echo "--- End of $JSON_CONFIG ---"

    - name: Prepare Android Resources (e.g., Icon)
      run: |
        ANDROID_SRC_DIR="src"
        mkdir -p "${ANDROID_SRC_DIR}/res/drawable"
        ICON_SOURCE="data/icon.png"
        ICON_DEST="${ANDROID_SRC_DIR}/res/drawable/icon.png"
        if [ -f "$ICON_SOURCE" ]; then
          cp "$ICON_SOURCE" "$ICON_DEST"
          echo "Copied icon from '$ICON_SOURCE' to '$ICON_DEST'"
        else
          echo "Warning: Icon source '$ICON_SOURCE' not found. App might lack an icon or use a default."
        fi

    - name: Install Qt ${{ env.QT_VERSION }} for Desktop (Host Build Tools)
      run: |
        echo "Installing Qt Host tools (Desktop Linux gcc_64)..."
        python -m aqt install-qt linux desktop ${{ env.QT_VERSION }} gcc_64 \
          --outputdir ${{ github.workspace }}/qt_host \
          --archives Tools Core Network Concurrent Widgets Gui Test Linguist

        # *** ENHANCED DEBUGGING: Check what was actually created ***
        echo "--- Debugging Qt Host Installation ---"
        echo "Exit code of aqt install: $?" # Check the exit code explicitly

        HOST_QT_BASE_DIR="${{ github.workspace }}/qt_host"
        echo "Listing contents of base output directory: $HOST_QT_BASE_DIR"
        ls -la "$HOST_QT_BASE_DIR"

        HOST_QT_VERSION_DIR="$HOST_QT_BASE_DIR/${{ env.QT_VERSION }}"
        echo "Checking if version directory exists: $HOST_QT_VERSION_DIR"
        if [ -d "$HOST_QT_VERSION_DIR" ]; then
          echo "Listing contents of version directory:"
          ls -la "$HOST_QT_VERSION_DIR"
        else
          echo "ERROR: Version directory '$HOST_QT_VERSION_DIR' was NOT created."
          # Attempt listing base dir again
          echo "Listing base dir '$HOST_QT_BASE_DIR' again:"
          ls -la "$HOST_QT_BASE_DIR"
          exit 1 # Fail the step explicitly if the expected dir is missing
        fi

        HOST_QT_ARCH_DIR="$HOST_QT_VERSION_DIR/gcc_64"
        echo "Checking if arch directory exists: $HOST_QT_ARCH_DIR"
        if [ -d "$HOST_QT_ARCH_DIR" ]; then
          echo "Listing contents of arch directory:"
          ls -la "$HOST_QT_ARCH_DIR"
        else
           echo "ERROR: Arch directory '$HOST_QT_ARCH_DIR' was NOT created."
           exit 1 # Fail the step
        fi

        HOST_QT_BIN_DIR="$HOST_QT_ARCH_DIR/bin"
        echo "Checking if bin directory exists: $HOST_QT_BIN_DIR"
        if [ -d "$HOST_QT_BIN_DIR" ]; then
          echo "Listing contents of bin directory:"
          ls -la "$HOST_QT_BIN_DIR"
          echo "Checking specifically for androiddeployqt:"
          ls -la "$HOST_QT_BIN_DIR/androiddeployqt" || echo "WARNING: androiddeployqt executable not found in bin directory!"
        else
           echo "ERROR: Bin directory '$HOST_QT_BIN_DIR' was NOT created."
           exit 1 # Fail the step
        fi
        echo "--- End Debugging Qt Host Installation ---"

    - name: Install Qt ${{ env.QT_VERSION }} for Android (Target Libraries)
      run: |
        echo "Installing Qt Target libraries (Android arm64_v8a)..."
        python -m aqt install-qt linux android ${{ env.QT_VERSION }} android_arm64_v8a \
          --outputdir ${{ github.workspace }}/qt_target \
          --archives qtbase qt5compat

    - name: Install Android SDK Command-Line Tools
      run: |
        echo "Setting up Android SDK directories..."
        mkdir -p $ANDROID_HOME/cmdline-tools
        echo "Downloading command-line tools..."
        wget -q ${{ env.ANDROID_CMDLINE_TOOLS_VERSION_URL }} -O cmdline-tools.zip
        echo "Extracting command-line tools..."
        unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        rm cmdline-tools.zip
        echo "Android command-line tools installed to $ANDROID_HOME/cmdline-tools/latest"
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        echo "SDK tool paths added to GITHUB_PATH"

    - name: Accept Android SDK Licenses
      run: |
        echo "Accepting Android SDK licenses..."
        yes | sdkmanager --licenses
        echo "Licenses accepted."

    - name: Install Android SDK Components (Platform, Build Tools, NDK)
      run: |
        echo "Installing Android SDK components..."
        yes | sdkmanager --install "platform-tools" \
                                   "platforms;${{ env.ANDROID_PLATFORM }}" \
                                   "build-tools;${{ env.ANDROID_BUILD_TOOLS_VERSION }}" \
                                   "ndk;${{ env.ANDROID_NDK_VERSION }}"
        echo "Android SDK components installed."
        NDK_PATH="$ANDROID_SDK_ROOT/ndk/${{ env.ANDROID_NDK_VERSION }}"
        echo "Setting ANDROID_NDK_ROOT=$NDK_PATH"
        echo "ANDROID_NDK_ROOT=$NDK_PATH" >> $GITHUB_ENV

    - name: Validate Android Environment
      run: |
        echo "--- Android Environment Validation ---"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        ls -l $ANDROID_SDK_ROOT
        echo "ANDROID_NDK_ROOT: $ANDROID_NDK_ROOT"
        ls -l $ANDROID_NDK_ROOT || echo "NDK directory listing failed."
        echo "Checking key tools in PATH:"
        which sdkmanager
        which adb || echo "adb not in PATH yet"
        which ndk-build || echo "ndk-build not found in PATH (expected)"
        java -version
        echo "Current PATH (before adding Qt Host): $PATH"
        echo "--- Validation Complete ---"

    - name: Add Qt Host Tools to PATH
      run: |
        QT_HOST_BIN_DIR="${{ github.workspace }}/qt_host/${{ env.QT_VERSION }}/gcc_64/bin"
        echo "Adding Qt Host bin to GITHUB_PATH: $QT_HOST_BIN_DIR"
        # Verify directory exists before adding to PATH
        if [ ! -d "$QT_HOST_BIN_DIR" ]; then
           echo "ERROR: Qt Host bin directory '$QT_HOST_BIN_DIR' not found! Cannot add to PATH."
           exit 1
        fi
        echo "$QT_HOST_BIN_DIR" >> $GITHUB_PATH
        echo "Verifying androiddeployqt existence again in $QT_HOST_BIN_DIR:"
        ls -la "$QT_HOST_BIN_DIR/androiddeployqt" || echo "WARNING: androiddeployqt check failed in Add Path step!"

    - name: Run androiddeployqt to Generate Gradle Project
      env:
        Qt6_DIR: ${{ github.workspace }}/qt_target/${{ env.QT_VERSION }}/android_arm64_v8a
      run: |
        echo "--- Running androiddeployqt ---"
        echo "Using Qt Host Tools from PATH"
        echo "Using Qt Target Libs from: $Qt6_DIR"
        echo "Current PATH: $PATH"
        QT_HOST_BIN_DIR_IN_STEP="${{ github.workspace }}/qt_host/${{ env.QT_VERSION }}/gcc_64/bin"
        echo "Verifying androiddeployqt existence one more time in $QT_HOST_BIN_DIR_IN_STEP:"
        ls -la "$QT_HOST_BIN_DIR_IN_STEP/androiddeployqt" || echo "WARNING: androiddeployqt check failed *inside* Run step!"
        echo "Result of which androiddeployqt:"
        which androiddeployqt || echo "'which' command failed to find androiddeployqt"
        echo "Result of command -v androiddeployqt:"
        command -v androiddeployqt || echo "'command -v' failed to find androiddeployqt"

        if ! command -v androiddeployqt &> /dev/null; then
            echo "ERROR: androiddeployqt command not found! Check GITHUB_PATH step and file existence/permissions."
            exit 1
        fi

        echo "Creating build directory: build-android"
        mkdir -p build-android

        echo "Executing androiddeployqt..."
        androiddeployqt \
          --input qt_for_python_android_deploy.json \
          --output build-android \
          --android-platform ${{ env.ANDROID_PLATFORM }} \
          --jdk "$JAVA_HOME" \
          --gradle \
          --verbose

        echo "--- androiddeployqt finished ---"
        echo "Listing generated project structure:"
        ls -l build-android

    - name: Build APK with Gradle
      working-directory: ./build-android
      run: |
        echo "--- Building Android Project with Gradle ---"
        echo "Current directory: $(pwd)"
        if [ ! -f "./gradlew" ]; then
           echo "ERROR: gradlew script not found in $(pwd). androiddeployqt might have failed."
           exit 1
        fi
        echo "Making gradlew executable..."
        chmod +x ./gradlew

        echo "Running Gradle build (assembleDebug)..."
        ./gradlew assembleDebug --info
        echo "--- Gradle build finished ---"

    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MolarMass-Android-Debug-APK
        path: ./build-android/build/outputs/apk/debug/*.apk
        if-no-files-found: error
