# .github/workflows/android-qt-build.yml

name: Build Android APK (Qt for Python)

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-android-qt:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out code
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Set up Java
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 3: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Step 4: Install Python Dependencies
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyside6 molmass

    # Step 5: Verify JSON config exists
    - name: Verify JSON config exists
      run: |
        if [ ! -f qt_for_python_android_deploy.json ]; then
          echo "ERROR: qt_for_python_android_deploy.json not found!"
          exit 1
        fi
        echo "qt_for_python_android_deploy.json found."
        cat qt_for_python_android_deploy.json

    # Step 6: Prepare Android Resources
    - name: Prepare Android Resources
      run: |
        mkdir -p src/res/drawable
        if [ -f "data/icon.png" ]; then
          cp data/icon.png src/res/drawable/icon.png
          echo "Copied icon from data/icon.png to src/res/drawable/"
        else
          echo "Warning: data/icon.png not found."
        fi

    # --- Environment Setup ---
    # Step 7: Install Qt for Android using install-qt-action
    - name: Install Qt for Android
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: 'linux'             # Host OS
        target: 'android'         # Target Platform
        arch: 'android_arm64_v8a' # Target ABI
        # Request necessary modules for the Android target build
        modules: 'qtbase qttools'
        # Optional: cache: 'true'

    # Step 8: Setup Android SDK components
    # Ensures SDK tools/platforms needed by Qt/Gradle are present
    - name: Setup Android SDK components
      uses: android-actions/setup-android@v3

    # Step 9: Run androiddeployqt
    # Use the Qt path provided by install-qt-action (check logs for exact variable name)
    - name: Run androiddeployqt
      run: |
        mkdir -p build-android
        echo "Using Qt directory (check logs for actual var): $Qt6_DIR or $QT_DIR"
        # Adjust variable if needed (e.g., $QT_DIR)
        # Also, the path might be slightly different for cross-compilation setups
        # Sometimes it's in a target-specific subdirectory. Let's try the base path first.
        $Qt6_DIR/bin/androiddeployqt \
          --input qt_for_python_android_deploy.json \
          --output build-android \
          --android-platform android-33 \
          --gradle

    # Step 10: Build with Gradle
    - name: Build with Gradle
      working-directory: ./build-android
      run: |
        chmod +x ./gradlew
        # Gradle needs ANDROID_SDK_ROOT/ANDROID_NDK_ROOT (check if set by actions)
        ./gradlew assembleDebug

    # Step 11: Upload APK artifact
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: MolarMass-Android-Debug-APK
        path: ./build-android/build/outputs/apk/debug/*.apk
        if-no-files-found: error
