name: Build Android APK (Qt for Python)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android-qt:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyside6==6.5.0
        pip install molmass aqtinstall beautifulsoup4 bs4 certifi charset-normalizer defusedxml humanize idna patch py7zr requests semantic-version soupsieve typing-extensions urllib3

    - name: Verify JSON config exists
      run: |
        if [ ! -f qt_for_python_android_deploy.json ]; then
          echo "ERROR: qt_for_python_android_deploy.json not found!"
          exit 1
        fi
        echo "qt_for_python_android_deploy.json found."
        cat qt_for_python_android_deploy.json

    - name: Prepare Android Resources
      run: |
        mkdir -p src/res/drawable
        if [ -f "data/icon.png" ]; then
          cp data/icon.png src/res/drawable/icon.png
          echo "Copied icon from data/icon.png to src/res/drawable/"
        else
          echo "Warning: data/icon.png not found. App might lack an icon."
        fi

    - name: Install Qt for Desktop (Host Tools)
      run: |
        python -m aqt install-qt linux desktop 6.5.0 gcc_64 --outputdir ${{ github.workspace }}/qt_host/Qt

    - name: Install Qt for Android (Target Libraries)
      run: |
        python -m aqt install-qt linux android 6.5.0 android_arm64_v8a --outputdir ${{ github.workspace }}/qt_target/Qt

    - name: Install Android Command-Line Tools
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

    - name: Accept Android SDK Licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android SDK components manually
      run: |
        echo "Installing Android SDK components..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.1.8937393"
        echo "Android SDK components installed."

    - name: Validate Android SDK installation
      run: |
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
        echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT"
        echo "PATH=$PATH"

        if [ -z "$ANDROID_SDK_ROOT" ]; then
          echo "ERROR: ANDROID_SDK_ROOT is not set!"
          exit 1
        fi

        if [ -z "$ANDROID_NDK_ROOT" ]; then
          echo "ERROR: ANDROID_NDK_ROOT is not set!"
          exit 1
        fi

        ls -l $ANDROID_SDK_ROOT
        ls -l $ANDROID_NDK_ROOT

    - name: Run androiddeployqt
      env:
        Qt6_DIR: ${{ github.workspace }}/qt_target/Qt/6.5.0/android_arm64_v8a
        PATH: ${{ github.workspace }}/qt_host/Qt/6.5.0/gcc_64/bin:$PATH
      run: |
        echo "--- Running androiddeployqt ---"
        if ! command -v androiddeployqt &> /dev/null; then
            echo "ERROR: androiddeployqt command not found in PATH!"
            exit 1
        fi
        mkdir -p build-android
        androiddeployqt \
          --input qt_for_python_android_deploy.json \
          --output build-android \
          --android-platform android-33 \
          --gradle \
          --verbose

    - name: Build with Gradle
      working-directory: ./build-android
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug --info

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: MolarMass-Android-Debug-APK
        path: ./build-android/build/outputs/apk/debug/*.apk
        if-no-files-found: error
